# Generated by Django 3.1.3 on 2020-12-15 06:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('downloads', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.IntegerField()),
                ('year', models.IntegerField()),
                ('downloads', models.IntegerField(default=0, verbose_name=django.contrib.auth.models.User)),
                ('upload_time', models.DateTimeField()),
                ('author', models.ForeignKey(default=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default='Без группы', on_delete=django.db.models.deletion.SET_DEFAULT, to='LabArkApp.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
