# Generated by Django 3.1.3 on 2020-12-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabArkApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='variant',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
