# Generated by Django 3.1.3 on 2020-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabArkApp', '0002_auto_20201215_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
