# Generated by Django 3.1.2 on 2020-12-29 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LabArkApp', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='downloads',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='lab',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lab',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lab',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabArkApp.category'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='variant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lab',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
