# Generated by Django 3.1.2 on 2020-12-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabArkApp', '0007_auto_20201229_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userpic',
            field=models.ImageField(default='default.png', upload_to='userpics'),
        ),
    ]
