# Generated by Django 3.1.2 on 2021-01-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabArkApp', '0010_auto_20210128_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
